### ISSUE TITLE
Add support for docker-engine

### ISSUE THREAD

**Issue by rtoma** [garethr/garethr-docker#281]
Docker package for RHEL has been renamed. It was called docker-io, but with 1.7.0 (maybe earlier?) its called docker-engine.

Workaround in hiera:
```
docker::package_name: 'docker-engine'
```

**Comment by garethr** [comment]
Thanks for the heads-up. I'll verify this when I get a moment (currently travelling and holidaying). Do you have a reference to this change anywhere?

**Comment by alanlaird** [comment]
https://docs.docker.com/installation/centos/ includes links to https://get.docker.com/rpm/1.7.0/centos-7/RPMS/x86_64/docker-engine-1.7.0-1.el7.centos.x86_64.rpm

**Comment by zxjinn** [comment]
I concur with this package name change, and it's not just for RHEL either. See #310 for more information about the potential modifications needed, and a link to a Docker blogpost about the change.

**Comment by garethr** [comment]
Ah, so this is for the docker inc packages.

The current situation is that for Debian based distros the module uses the Docker packages, at least by default. You can change this behaviour by setting `use_upstream_package_source` to false.

For RedHat based systems, it uses the the distro packages (or whatever repos you have installed yourself), or it can optionally use the ones from epel. Up until now Docker didn't have an official yum repository.

My plan is for a v5.0 of the module sometime soon, which will tidy this up, and support the new repos by default. You can track that effort in https://github.com/garethr/garethr-docker/tree/new-docker-repos

**Comment by snufalufagus** [comment]
rtoma - Thanks for the hiera workaround on this issue.

**Comment by jovandeginste** [comment]
Apparently, (at least in CentOS 7) the package is back as 'docker':

```
# yum info docker
<...>
Name        : docker
Arch        : x86_64
Version     : 1.7.1
Release     : 108.el7.centos
Size        : 30 M
Repo        : installed
From repo   : centos-extras
```

FWIW, this release integrates with FirewallD (which I was really waiting for)

**Comment by PierreR** [comment]
On CentOS 7, the package is indeed named`docker` but for a reason I quite don't get, the docker daemon won't start when using it.

It would be more consistent to default to docker package whenever  `use_upstream_package_source` is true as it is the case for `debian`. As a plus this would follow the [docker centos installation guideline`](https://docs.docker.com/installation/centos/).

Any progress on that front ? 

I am a bit stuck because well ... as I said the `docker` daemon doesn't seem to start when using the current setting with CentOS 7. There is no error message, the daemon starts and then gets killed. 

On the other hand if I switch to use `docker-engine` directly from the docker package it works flawlessly.

**Comment by garethr** [comment]
@PierreR if you could try out the branch from #311 and see if this resolves your problems. Any testing there would be great as I plan to merge it soon.

**Comment by PierreR** [comment]
@garethr I will try. I need to update first (I am still using a docker version that does not require puppet >=3.4)

**Comment by garethr** [comment]
Note that master now supports the correct packages from the various new repos.
