### ISSUE TITLE
CentOS 7 and Docker version 1.9.*

### ISSUE THREAD

**Issue by koysti** [garethr/garethr-docker#383]
I'm using CentOS 7 and i need Docker version 1.9.1. On default the module installs version 1.8.2. What i need to do that the module installs Docker version 1.9.1.? 

Run log:
```
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y --enablerepo=extras install docker-1.9.1' returned 1: Error: Nothing to do
Error: /Stage[main]/Docker::Install/Package[docker]/ensure: change from 1.8.2-7.el7.centos to 1.9.1 failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y --enablerepo=extras install docker-1.9.1' returned 1: Error: Nothing to do
Notice: /Stage[main]/Docker::Service/File[/etc/sysconfig/docker-storage]: Dependency Package[docker] has failures: true
```

docker.pp
```
class { 'docker':
  use_upstream_package_source => false,
  package_name => 'docker',
  version => '1.9.1'
}
```

**Comment by garethr** [comment]
Ah, the problem here is that you're not using the upstream (ie. docker provided) packages and your distro or internal repo doesn not have 1.9.1 available.

I've just verified I get 1.9.1 if I just use the following on Centos 7.0 using master.

```puppet
include 'docker'
```

Docker moves quite quickly and if you want the latest version then using the upstream repos is prefered.
