### ISSUE TITLE
install failed on RHEL7

### ISSUE THREAD

**Issue by Thorndike** [garethr/garethr-docker#462]
On a vanilla RHEL 7 server the installation of docker fails with 

`Error: Execution of '/usr/bin/yum -d 0 -e 0 -y  install docker-engine' returned 1: No such command: . Please use /usr/bin/yum --help
Error: /Stage[main]/Docker::Install/Package[docker]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y  install docker-engine' returned 1: No such command: . Please use /usr/bin/yum --help`

What I don't understand is that i can manually execute 
`/usr/bin/yum -d 0 -e 0 -y  install docker-engine`
without any error and get docker installed. I have configured a docker.repo with the puppet to point to yum.dockerrepo.org and the installation code for docker is:

`  class { 'docker':
    require => Yumrepo["dockerrepo"],
    use_upstream_package_source => false,
    service_name => 'docker',
    package_name => 'docker-engine',
    docker_command => 'docker',
    repo_opt => '',
    extra_parameters => "-H 0.0.0.0:2375 --insecure-registry my-registry.de --dns #.#.#.# --dns #.#.#.#",
  }`

RHEL 7.2
Puppet 4.3.2
├── garethr-docker (v5.1.0)

**Comment by roller1187** [comment]
I'm also seeing this issue. Is there an ETA for a fix? Thanks!

**Comment by garethr** [comment]
@roller1187 do you have details about the RHEL version?

**Comment by roller1187** [comment]
@garethr it's actually CentOS 7, but same difference :)

$ hostnamectl
    Static hostname: XXXX
    Icon name: computer-vm
    Chassis: vm
    Machine ID: XXXX
    Boot ID: XXXX
    Virtualization: vmware
    Operating System: CentOS Linux 7 (Core)
    CPE OS Name: cpe:/o:centos:centos:7
    Kernel: Linux 3.10.0-229.el7.x86_64
    Architecture: x86-64

**Comment by roller1187** [comment]
@garethr Actually, it looks like this issue was fixed by a recent PR:

https://github.com/garethr/garethr-docker/pull/437

Sorry for the false alarm!

**Comment by garethr** [comment]
@roller1187 thanks for letting me know, glad we fixed the issue.

**Comment by nnarcise** [comment]
I am experiencing this issue trying to install docker on rhel 7
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y --enablerepo=rhel7-extras install docker' returned 1: Error getting repository data for rhel7-extras, repository not found

But my RHEL repo ID's are different
Repo ID:   rhel-7-server-extras-rpms

No problems installing on CentoS 7 - just RHEL7 due to the repo names it looking for are different

I also was looking to install the Commerically Supported version of Docker and thought using the "use_upstream_package_source => false," would stop from checking this but still looking in my rhel repos. I am able to install docker from the command line using both the rhel repo and dockers using "curl -sSL https://get.docker.com/ | sh"
