### ISSUE TITLE
Error while evaluating a Resource Statement, Apt::Source[docker]

### ISSUE THREAD

**Issue by kr428** [garethr/garethr-docker#725]
Folks;

pardon if this is a known issue. Running into trouble trying to use puppet/docker on Ubuntu 16.04:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[docker]:
  has no parameter named 'required_packages'
  has no parameter named 'key_source'
  has no parameter named 'include_src' at /etc/puppetlabs/code/environments/production/modules/docker/manifests/install.pp:23 on node frontendtest
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
`
Not really sure where to look next. Don't have much declaration for puppet docker class in there so far except for this:

`  class { 'docker':
    docker_users => ['remote'],
  }`

Where to look to figure out what's wrong here?
TIA,
Kristian

**Comment by cajdavidson** [comment]
@kr428 I ran into the same problem, I think that it was due to me updating the puppet-apt module that I was using, there is a pull request outstanding to fix this issue[0], I manually implemented these changes to the module on my puppetmaster and all works as expected. You can probably do that too, at least until the changes are merged.

[0] https://github.com/garethr/garethr-docker/pull/713

**Comment by LongLiveCHIEF** [comment]
I've forked garethr/docker, and this issue should be fixed in the latest release of `hackerhappyhour/docker`.  Give it a shot, and let me know if you have any issues here: https://github.com/HackerHappyHour/hackerhappyhour-docker/issues

**Comment by kr428** [comment]
@cajdavidson Followed your approach and got it to work this way, thanks a bunch! :)
